language: cpp
#run on latest container based infrastructure
sudo: false

compiler:
  - clang
  - gcc

env:
  - MPI=mpich
  - MPI=openmpi

matrix:
  allow_failures:

branches:
  only:
    - master

#workaround for container based packages
addons:
  apt:
    packages:
      - openmpi
      - mpich


before_install:
  - echo "not using sudo"

install:
  - git clone https://github.com/YetAnotherMinion/googletest.git /tmp/googletest

#export some environmental variables
before_script:

script: make -C ./c-misc/DS\ projects

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d55687e505a435ed86dc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
