language: cpp
#run on latest container based infrastructure
sudo: false

compiler:
  - clang
  - gcc

matrix:
  allow_failures:

branches:
  only:
    - master

#workaround for container based packages
addons:
  apt:
    packages:
      - python
      - pip


before_install:
  - echo "not using sudo"

install:
  - git clone https://github.com/YetAnotherMinion/googletest.git /tmp/googletest
  - git clone https://github.com/YetAnotherMinion/testcases.git /tmp/testcases

#export some environmental variables
before_script:
  - mkdir c-misc/DS\ projects/obj
  - mkdir c-misc/DS\ projects/bin

script: 
  - make -C ./c-misc/DS\ projects
  - ./CodeAbbey/test_solutions.sh /tmp/testcases/CodeAbbey

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d55687e505a435ed86dc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
